#!/bin/bash

set -e
set -o pipefail

#   A script that runs loads a config file and runs a wrapper script for ANGSD

#   Define a usage message
function usage() {
    echo -e "\
Usage:  $(basename $0) <wrapper> <config> \n\
where:  <wrapper> is one of SFS, 2DSFS, Abbababa, Ancestral, Genotypes, Thetas, Inbreeding
and:    <config> is the corresponding configuration file \n\
\n\
The following is a list of calls and what they do: \n\
    SFS         Site frequency spectrum \n\
    2DSFS       2D Site frequency spectrum and Fst estimations \n\
    Abbababa    Abba baba test \n\
    Ancestral   Extract ancestral sequence from BAM file \n\
    Genotypes   Genotype likelihood estimations \n\
    PCA         Principal component analysis \n\
    Thetas      Estimate thetas and calculate neutrality test statistics \n\
    Inbreeding  Use ngsF to calculate per-individual inbreeding coefficients \n\
    Admixture   Perform admixture analysis \n\
\n\
To upgrade the dependencies, please run \n\
\n\
    $(basename $0) upgrade dependencies \n\
\n\
To start the Shiny graphing interface, please run \n\
    $(basename $0) shiny graphing \n\
" >&2
    exit 1
}

#   Where is angsd-wrapper located?
SOURCE=$(dirname "$0")

#   Run some checks
if [[ ! -d "${SOURCE}"/dependencies ]] # Are we missing the dependencies directory?
then
    if [[ ! "$1" == 'setup' ]] # If we're not running the setup routine
    then
        echo -e "\
Welcome to $(basename $0)! \n\
To set up, please run \n\
\n\
    ./$(basename $0) setup please \n\
" >&2
        exit 1
    fi
elif [[ "$#" -lt 2 ]] # Otherwise, are we missing our two arguments
then
    usage # If so, display the usage message
fi

WRAPPER="$1"
CONFIG="$2"

case "${WRAPPER}" in
    "setup" )
        if ! [ "${CONFIG}" == "please" ]
        then
            echo "Ask nicely"
            exit 1
        fi
        bash Wrappers/Setup.sh
        ;;
    "SFS" )
        #   Run the site frequency spectrum wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Site_Frequency_Spectrum.sh "${CONFIG}" "${SOURCE}"
        ;;
    "2DSFS" )
        #   Run the 2D site frequency spectrum wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/2D_SFS_Fst.sh "${CONFIG}" "${SOURCE}"
        ;;
    "Abbababa" )
        #   Run the ABBA-BABA wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Abbababa.sh "${CONFIG}" "${SOURCE}"
        ;;
    "Ancestral" )
        #   Run the ancestral sequence wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Ancestral_Sequence.sh "${CONFIG}" "${SOURCE}"
        ;;
    "Genotypes" )
        #   Run the genotypes wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Genotypes.sh "${CONFIG}" "${SOURCE}"
        ;;
    "PCA" )
        #   Run the PCA wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Principal_Component_Analysis.sh "${CONFIG}" "${SOURCE}"
        ;;
    "Thetas" )
        #   Run the Thetas wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Thetas.sh "${CONFIG}" "${SOURCE}"
        ;;
    "Inbreeding" )
        #   Run the Inbreeding wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Inbreeding_Coefficients.sh "${CONFIG}" "${SOURCE}"
        ;;
    "Admixture" )
        #   Run the Admixture wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash "${SOURCE}"/Wrappers/Admixture.sh "${CONFIG}" "${SOURCE}"
        ;;
    "help" )
        bash "${SOURCE}"/Wrappers/Help.sh
        ;;
    "upgrade" )
        bash "${SOURCE}"/Wrappers/Upgrade.sh "${SOURCE}"
        ;;
    "shiny" )
        Rscript "${SOURCE}"/Wrappers/startShiny.R "${SOURCE}"
        ;;
    "test" )
        bash "${SOURCE}"/Wrappers/test.sh
        ;;
    * )
        usage
        ;;
esac
