#!/bin/bash

set -e
set -o pipefail

#   A script that runs loads a config file and runs a wrapper script for ANGSD

#   Define a usage message
function usage() {
    echo -e "\
Usage:  ./angsd-wrapper.sh <wrapper> <config> \n\
where:  <wrapper> is one of SFS, 2DSFS, ABBA_BABA, ANC_SEQ, Genotypes, Thetas, ngsF
and:    <config> is the corresponding configuration file \n\
\n\
The following is a list of calls and what they do: \n\
    SFS         Site Frequency Spectrum \n\
    2DSFS      2D Site Frequency Spectrum \n\
    ngsFST      FST calculations, THIS NEEDS TO BE \n\
                    RUN AFTER 2D SFS
    ABBA_BABBA  ABBA_BABBA Test \n\
    ANC_SEQ     Extract Ancestral Sequence from BAM file \n\
    Genotypes   Genotype Calling \n\
    Thetas      Estimate thetas and perform neutrality test statistics \n\
    ngsF        Use ngsF to calculate per-individual inbreeding coefficients \n\
    ngsAdmix    Run ngsAdmix
\n\
For an interactive help, type 'help me' without the quotes \n\
" >&2
    exit 1
}


#   Check to see if Wrappers directory is one level below this
if ! [[ -d 'Wrappers' ]]
then
    echo "Cannot find 'Wrappers' directory, exiting" >&2
    exit 1
fi

#   First use, look for 'dependencies' directory
if ! [[ -d 'dependencies' ]] && [[ -z "$1" || "$1" -ne 'setup' ]]
then
    echo $1
    echo -e "\
        Welcome to angsd-wrapper! \n\
To set up, please run \n\
\n\
    ./angsd-wrapper.sh setup please \n\
" >&2
    exit 1
fi

#   Check to see if there are the correct number of arguments
if [ "$#" -lt 2 ]
then
    usage
fi

WRAPPER="$1"
CONFIG="$2"

case "${WRAPPER}" in
    "setup" )
        if ! [ "${CONFIG}" == "please" ]
        then
            echo "Ask nicely"
            exit 1
        fi
        bash Wrappers/Setup.sh
        ;;
    "SFS" )
        #   Run the site frequency spectrum wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/Site_Frequency_Spectrum.sh "${CONFIG}"
        ;;
    "2DSFS" )
        #   Run the 2D site frequency spectrum wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/2D_Site_Frequency_Spectrum.sh "${CONFIG}"
        ;;
    "ngsFST" )
        #   Run the ngsFST wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/ngsFST.sh "${CONFIG}"
        ;;
    "ABBA_BABA" )
        #   Run the ABBA-BABA wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/ABBA_BABA.sh "${CONFIG}"
        ;;
    "ANC_SEQ" )
        #   Run the ancestral sequence wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/Ancestral_Sequence.sh "${CONFIG}"
        ;;
    "Genotypes" )
        #   Run the genotypes wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/Genotypes.sh "${CONFIG}"
        ;;
    "Thetas" )
        #   Run the thetas wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/Thetas.sh "${CONFIG}"
        ;;
    "ngsF" )
        #   Run the ngsF wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/ngsF.sh "${CONFIG}"
        ;;
    "ngsAdmix" )
        #   Run the ngsAdmix wrapper script
        if ! [[ -f "${CONFIG}" ]]
        then
            echo "Please specify a valid config file"
            exit 1
        fi
        bash Wrappers/ngsAdmix.sh "${CONFIG}"
        ;;
    "help" )
        bash Wrappers/Help.sh
        ;;
    "test" )
        bash Wrappers/test.sh
        ;;
    * )
        usage
        ;;
esac
