#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold explanantions for variables used in ANGSD-Wrapper

BAM=`echo -e "\
A list of BAM files to be used by ANGSD \n\
This list should have the full file path to each file \n\
example: \n\
    /home/directory/file1.bam \n\
    /home/directory/file2.bam \n\
We require this kind of input for all methods \n\
" >&1`

OUT=