#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the 2D Site Frequency Spectrum and Fst estimations
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Ancestral sequence
ANC_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/2DSFS
SCRATCH=

#   Region being looked at?
REGIONS=
##############################################################################################

#   What is group 1?
GROUP_1=

#   Sample list for group 1
G1_SAMPLE_LIST=

#   Inbreeding coefficients for group 1
G1_INBREEDING=

#   What is group 2?
GROUP_2=

#   Sample list for group 2
G2_SAMPLE_LIST=

#   Inbreeding coefficients for group 2
G2_INBREEDING=

#   2D Site Frequency Spectrum and ngsFST Parameters
#       Listed below are the defaults, please modify for your samples
DO_SAF=2
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
MIN_IND1=1
MIN_IND2=1
GT_LIKELIHOOD=2
MIN_MAPQ=30
N_CORES=16
DO_MAJORMINOR=1
DO_MAF=1
DO_POST=1
BLOCK_SIZE=20000
RELATIVE=1
MAX_LIKE=1
OVERRIDE=false
