#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for ABBA BABA
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Name of the project
PROJECT=

#   Where do we put the outfiles?
#      Note, the final outdirectory will be
#      ${SCRATCH}/${PROJECT}/ABBABABA
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=
##############################################################################################

#   Fasta file to be used as an outgroup
#       This can be generated using the ANC_SEQ function of angsd-wrapper
OUTGROUP=

#   ABBA BABA Parameters
#       Listed below are the defaults, please modify for your samples
DO_CONSENSUS=0
DO_FASTA=2
DO_COUNTS=1
DO_ABBABABA=1
REMOVE_TRANS=0
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
MIN_IND=1
MIN_MAPQ=30
N_CORES=32
CHECK_BAM_HEADERS=0
BLOCKSIZE=1000
SORTED=false
CONFIG=false
