#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for ABBA BABA
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Name of the project
PROJECT=

#   Where do we put the outfiles?
#      Note, the final outdirectory will be
#      ${SCRATCH}/${PROJECT}/ABBABABA
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=

#   Parameters that are specified in Common_Config
#       Use only uniquely-mapped reads
UNIQUE_ONLY=0
#       Set the minimum base quality
MIN_BASEQUAL=20
#       Set the minimum number of individuals required
MIN_IND=1
#       Set the minimum mapping quality for a base to be used
MIN_MAPQ=30
#       Set the number of threads to be used
N_CORES=32
##############################################################################################

#   Fasta file to be used as an outgroup
#       This can be generated using the ANC_SEQ function of angsd-wrapper
OUTGROUP=

#   ABBA BABA Parameters
#       Listed below are the defaults, please modify for your samples
#       Count allele frequencies
DO_COUNTS=1
#       Perform Abbababa analysis
DO_ABBABABA=1
#       Remove transitions from sample
REMOVE_TRANS=0
#       Set the size for each block
BLOCKSIZE=1000

#   For advanced users who want to change arguments used by ANGSD (i.e. which SAF method is used)
#       Expected format is the same as how the flags and arguments are written on the command line:
#       '-flag1 arg1 -flag2 arg2 ...' 
ADVANCED_ARGS=''
