#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for generating an ancestral fasta file

#   Where is the ancestral BAM file?
ANC_BAM=

#   Are you using the Common_Config file?
COMMON=
