#!/bin/bash

set -e
set -o pipefail

#   Tell us where the files for graphing are:

#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   Name of the project
PROJECT=

#   Where do we put the outfiles?
#      Note, the final outdirectory will be
#      ${SCRATCH}/${PROJECT}/plots
SCRATCH=
##############################################################################################

#   Site Frequency Spectrum
#       This should be the Derived_SFS file
SFS_OUT=

#   Thetas Estimators
#       This should be the .pestPG file
THETAS_OUT=

##############################################################################################
#   The following graphing utilities are not yet implemented
#   They will be implemented shortly
##############################################################################################
#   Abbababa D-Test
#       This should be the .abbababa.txt file
ABBABABBA_OUT=

#   Fst Estimations
#       This should be the .fst file
FST_OUT=

#   Admixture
#       This should be the .qopt file
ADMIX_OUT=

#   Principle Component Analysis
#       This should be the _PCA.covar file
PCA_OUT=
##############################################################################################
