#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold common variables for angsd-wrapper

#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
#	This should end in '_.indF'
SAMPLE_INBREEDING=

#   Ancestral sequence
ANC_SEQ=

#   Reference sequence
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/<name_of_program/>
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=

#   Set common parameters for all methods
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
MIN_IND=1
GT_LIKELIHOOD=2
MIN_MAPQ=30
N_CORES=32
DO_MAJORMINOR=1
DO_GENO=32
DO_MAF=1
DO_POST=1
