#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold common variables for angsd-wrapper

#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
#	Use '.indF' file
SAMPLE_INBREEDING=

#   Ancestral sequence
ANC_SEQ=

#   Reference sequence
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/<name_of_program/>
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=
