#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold common variables for angsd-wrapper

#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
#	This should end in '_.indF'
SAMPLE_INBREEDING=

#   Ancestral sequence
ANC_SEQ=

#   Reference sequence
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/<name_of_program/>
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=

#   Set common parameters for all methods
#       Use only uniquely-mapped reads
UNIQUE_ONLY=0
#       Set the minimum base quality
MIN_BASEQUAL=20
#       Calculate base alignment quality
BAQ=1
#       Set the minimum number of individuals required
MIN_IND=1
#       Calculate genotype likelihoods
GT_LIKELIHOOD=2
#       Set the minimum mapping quality for a base to be used
MIN_MAPQ=30
#       Set the minimum mapping quality for a base to be used
N_CORES=32
#       Determine major and minor alleles
DO_MAJORMINOR=1
#       Call genotypes from genotype likelihoods
DO_GENO=32
#       Calculate allele frequencies
DO_MAF=1
#       Calculate the posterior probability
DO_POST=1
