#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Fst estimations
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Ancestral and Reference sequences
ANC_SEQ=
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/Fst
SCRATCH=

#   Region being looked at?
REGIONS=

#   Parameters that are specified in Common_Config
#       Use only uniquely-mapped reads
UNIQUE_ONLY=0
#       Set the minimum base quality
MIN_BASEQUAL=20
#       Calculate base alignment quality
BAQ=1
#       Calculate genotype likelihoods
GT_LIKELIHOOD=2
#       Set the minimum mapping quality for a base to be used
MIN_MAPQ=30
#       Set the minimum mapping quality for a base to be used
N_CORES=32
#       Determine major and minor alleles
DO_MAJORMINOR=1
#       Call genotypes from genotype likelihoods
DO_GENO=32
#       Calculate allele frequencies
DO_MAF=1
#       Calculate the posterior probability
DO_POST=1

##############################################################################################

#   What is group 1?
GROUP_1=

#   Sample list for group 1
G1_SAMPLE_LIST=

#   Inbreeding coefficients for group 1
G1_INBREEDING=

#   What is group 2?
GROUP_2=

#   Sample list for group 2
G2_SAMPLE_LIST=

#   Inbreeding coefficients for group 2
G2_INBREEDING=

#   FST Parameters
#       Listed below are the defaults, please modify for your samples
#       Generate site allele frequencies
DO_SAF=2
#       Set the minimum number of individuals required for group 1
MIN_IND1=4
#       Set the minimum number of individuals required for group 2
MIN_IND2=4
#       Overwrite any previously generated results
OVERRIDE=true
#       Calculate global Fst values
GLOBAL=true
#       Set the sliding window size
WIN=1000
#       Set the step size for sliding window analysis
STEP=500
