#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Fst estimations
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Ancestral and Reference sequences
ANC_SEQ=
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/Fst
SCRATCH=

#   Region being looked at?
REGIONS=

#   Parameters that are specified in Common_Config
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
GT_LIKELIHOOD=2
MIN_MAPQ=30
N_CORES=32
DO_MAJORMINOR=1
DO_MAF=1
DO_POST=1

##############################################################################################

#   What is group 1?
GROUP_1=

#   Sample list for group 1
G1_SAMPLE_LIST=

#   Inbreeding coefficients for group 1
G1_INBREEDING=

#   What is group 2?
GROUP_2=

#   Sample list for group 2
G2_SAMPLE_LIST=

#   Inbreeding coefficients for group 2
G2_INBREEDING=

#   FST Parameters
#       Listed below are the defaults, please modify for your samples
DO_SAF=2
MIN_IND1=4
MIN_IND2=4
OVERRIDE=true
GLOBAL=true
WIN=1000
STEP=500
