#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Site Frequency Spectrum
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
SAMPLE_INBREEDING=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/GenotypeLikelihoods
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=

#   Set common parameters for all methods
#       Use only uniquely-mapped reads
UNIQUE_ONLY=0
#       Set the minimum base quality
MIN_BASEQUAL=20
#       Calculate base alignment quality
BAQ=1
#       Set the minimum number of individuals required
MIN_IND=1
#       Calculate genotype likelihoods
GT_LIKELIHOOD=2
#       Set the minimum mapping quality for a base to be used
MIN_MAPQ=30
#       Set the number of threads to be used
N_CORES=32
#       Determine major and minor alleles
DO_MAJORMINOR=1
#       Call genotypes from genotype likelihoods
DO_GENO=32
#       Calculate allele frequencies
DO_MAF=1
#       Calculate the posterior probability
DO_POST=1

##############################################################################################

#   Genotypes Parameters
#       Listed below are the defaults, please modify for your samples
#       Set the minimum posterior value for calling genotypes
POST_CUTOFF=0.95
#       Set the maximum p-value for polymorphic sites
SNP_PVAL=1e-6
#       Output genotype likelihood frequency file
DO_GLF=2
