#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the NGS_F
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Ancestral and Reference sequences
ANC_SEQ=
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/ngsF
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=
##############################################################################################

#   ngsF Parameters
#       Listed below are the defaults, please modify for your samples
MIN_BASEQUAL=20
GT_LIKELIHOOD=1
DO_GLF=3
MIN_MAPQ=30
N_CORES=32
DO_MAJORMINOR=1
DO_MAF=1
SNP_PVAL=1e-6
OVERRIDE=false
MIN_EPSILON=1e-9
    #   Use the random number generator built into BASH
SEED=$RANDOM
