#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold the varialbes for the NGS Admixture

#   Name the project
PROJECT=

#   The Likelihood file
#       This is the .beagle.gz file from the Site Frequency Spectrum
LIKELIHOOD=

#   Where is ngsAdmix?
ADMIX_DIR=

#   ngsAdmix Parameters
#       Listed below are the defaults, please modify for your samples
K=5
N_CORES=32
MIN_MAF=0.05