#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the NGS_F

#   Name the project
PROJECT=SCN_ngsF

#   Define a list of samples
SAMPLE_LIST=${HOME}/sandbox/SCN_Tasks/scratch/real_out/SAMTools_Dedup/No19_BAM.txt

#   Ancestral and Reference sequences
ANC_SEQ=${HOME}/Shared/References/Reference_Sequences/Soybean_Cyst_Nematode/Heterodera_glycines_OP25_genome.fa
REF_SEQ=${HOME}/Shared/References/Reference_Sequences/Soybean_Cyst_Nematode/Heterodera_glycines_OP25_genome.fa

#   Where do we put the outfiles?
OUTDIR=${HOME}/sandbox/SCN_Tasks/scratch/real_out

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS="${HOME}/sandbox/SCN_Tasks/scratch/real_out/SAMTools_Dedup/regions.txt"

#   Where is ANGSD?
ANGSD_DIR=${HOME}/software/angsd

#   Where is ngsF?
NGSF_DIR=${HOME}/software/ngsF

#   ngsF Parameters
#       Listed below are the defaults, please modify for your samples
MIN_BASEQUAL=20
GT_LIKELIHOOD=1
DO_GLF=3
MIN_MAPQ=30
N_CORES=32
DO_MAJORMINOR=1
DO_MAF=1
SNP_PVAL=1e-6
OVERRIDE=false
MIN_EPSILON=1e-9
    #   Use the random number generator built into BASH
SEED=$RANDOM