#!/bin/bash

set -e
set -u
set -o pipefail

#   NOTE: This script is configured for use with the 2D Site Frequency Spectrum option in this package

#   Name the project
#       Please make the same as from the 2D Site Frequency Spectrum
PROJECT=

#   Where do we put the outfiles?
#       Note, the final outdirectory will be
#       ${SCRATCH}/${PROJECT}
#       Please make the same as from the 2D Site Frequency Spectrum
SCRATCH=

#   What is group 1?
#       Please make the same as from the 2D Site Frequency Spectrum
GROUP_1=

#   Sample list for group 1
#       Please make the same as from the 2D Site Frequency Spectrum
G1_SAMPLE_LIST=

#   SFS file for group 1
#       This is from the 2D Site Frequency Spectrum
G1_SFS="${SCRATCH}"/"${PROJECT}"/"${GROUP_1}"_Intergenic_Conditioned.sfs

#   What is group 2
#       Please make the same as from the 2D Site Frequency Spectrum
GROUP_2=

#   Sample list for group 2
#       Please make the same as from the 2D Site Frequency Spectrum
G2_SAMPLE_LIST=

#   SFS file for group 2
#       This is from the 2D Site Frequency Spectrum
G2_SFS="${SCRATCH}"/"${PROJECT}"/"${GROUP_2}"_Intergenic_Conditioned.sfs

#   Intersect file for groups 1 and 2
#       This is from the 2D Site Frequency Spectrum
INTERSECT="${SCRATCH}"/"${PROJECT}"/Intersect."${GROUP_1}"."${GROUP_2}"_intergenic.txt

#   2D SFS file for groups 1 and 2
#       This is from the 2D Site Frequency Spectrum
2DSFS="${SCRATCH}"/"${PROJECT}"/2DSFS_Intergenic."${GROUP_1}"."${GROUP_2}".sfs

#   Where is ngsPopGen stored?
NGS_POPGEN=

#   Where is the angsd-wrapper directory?
ANGSD_WRAPPER=

#   ngsFST Parameters
#       Listed below are the defaults, please modify for your samples
DO_SAF=2
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
MIN_IND1=1
MIN_IND2=1
GT_LIKELIHOOD=2
MIN_MAPQ=30
N_CORES=16
DO_MAJORMINOR=1
DO_MAF=1
BLOCK_SIZE=20000
