#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Principal Component Analysis
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/PCA
SCRATCH=

#   Region being looked at?
REGIONS=

#   Parameters that are specified in Common_Config
DO_MAF=2
DO_MAJORMINOR=1
DO_GENO=32
DO_POST=1
N_CORES=8
GT_LIKELIHOOD=2

##############################################################################################

#   Principal Component Analysis Parameters
#       Listed below are the defaults, please modify for your samples
NORM=0
CALL=0
N_SITES=100000
