#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Principal Component Analysis
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/PCA
SCRATCH=

#   Region being looked at?
REGIONS=

#   Parameters that are specified in Common_Config
#       Calculate genotype likelihoods
GT_LIKELIHOOD=2
#       Set the number of threads to be used
N_CORES=32
#       Determine major and minor alleles
DO_MAJORMINOR=1
#       Call genotypes from genotype likelihoods
DO_GENO=32
#       Calculate allele frequencies
DO_MAF=1
#       Calculate the posterior probability
DO_POST=1

##############################################################################################

#   Principal Component Analysis Parameters
#       Listed below are the defaults, please modify for your samples
#       Normalize by allele frequency
NORM=0
#       Perform genotype calling
CALL=0
#       Set the maximum number of sites to use for Principal Component Analysis
N_SITES=100000
