#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Site Frequency Spectrum
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
SAMPLE_INBREEDING=

#   Ancestral and Reference sequences
ANC_SEQ=
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/SFS
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=
##############################################################################################

#   Site Frequency Spectrum Parameters
#       Listed below are the defaults, please modify for your samples
DO_SAF=2
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
MIN_IND=1
GT_LIKELIHOOD=2
DO_GLF=2
MIN_MAPQ=30
N_CORES=32
DO_MAJORMINOR=1
DO_GENO=32
DO_MAF=1
DO_POST=1
OVERRIDE=false