#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Site Frequency Spectrum
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
SAMPLE_INBREEDING=

#   Ancestral and Reference sequences
ANC_SEQ=
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/SFS
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=

#   Parameters that are specified in Common_Config
#       Use only uniquely-mapped reads
UNIQUE_ONLY=0
#       Set the minimum base quality
MIN_BASEQUAL=20
#       Calculate base alignment quality
BAQ=1
#       Set the minimum number of individuals required
MIN_IND=1
#       Calculate genotype likelihoods
GT_LIKELIHOOD=2
#       Set the minimum mapping quality for a base to be used
MIN_MAPQ=30
#       Set the number of threads to be used
N_CORES=32
#       Determine major and minor alleles
DO_MAJORMINOR=1
#       Call genotypes from genotype likelihoods
DO_GENO=32
#       Calculate allele frequencies
DO_MAF=1
#       Calculate the posterior probability
DO_POST=1

##############################################################################################

#   Site Frequency Spectrum Parameters
#       Listed below are the defaults, please modify for your samples
#       Generate site allele frequencies
DO_SAF=2
#       Overwrite any previously generated results
OVERRIDE=true

#   For advanced users who want to change arguments used by ANGSD (i.e. which SAF method is used)
#       Expected format is the same as how the flags and arguments are written on the command line:
#       '-flag1 arg1 -flag2 arg2 ...' 
ADVANCED_ARGS=''
