#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Estimation of Thetas
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
SAMPLE_INBREEDING=

#   Ancestral and Reference sequences
ANC_SEQ=
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/Thetas
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=

#   Parameters that are specified in Common_Config
#       Use only uniquely-mapped reads
UNIQUE_ONLY=0
#       Set the minimum base quality
MIN_BASEQUAL=20
#       Calculate base alignment quality
BAQ=1
#       Set the minimum number of individuals required
MIN_IND=1
#       Calculate genotype likelihoods
GT_LIKELIHOOD=2
#       Set the minimum mapping quality for a base to be used
MIN_MAPQ=30
#       Set the number of threads to be used
N_CORES=32
#       Determine major and minor alleles
DO_MAJORMINOR=1
#       Calculate allele frequencies
DO_MAF=1

##############################################################################################

#   Pest file
#       This is the output from the site frequency spectrum wrapper
#       This should end in "_DerivedSFS.graph.me"
PEST=

#   Thetas Parameters
#       Listed below are the defaults, please modify for your samples
#       Generate site allele frequencies
DO_SAF=2
#       Overwrite any previously generated results
OVERRIDE=true
#       Perform sliding window Thetas calculations
SLIDING_WINDOW=false
#       Set the sliding window size
WIN=1000
#       Set the step size for sliding window analysis
STEP=500
