#!/bin/bash

set -e
set -u
set -o pipefail

#   A simple script to hold variables for the Estimation of Thetas
#   Are you using the Common_Config file?
#       If so, where is it?
COMMON=

##############################################################################################
#   If we aren't using the Common_Config file, specify these variables
#   If Common_Config is specified, leave these blank
#   Define a list of samples
SAMPLE_LIST=

#   Define a list of inbreeding coefficients
SAMPLE_INBREEDING=

#   Ancestral and Reference sequences
ANC_SEQ=
REF_SEQ=

#   Name the project
PROJECT=

#   Where do we put the outfiles?
    #   Note, the final outdirectory will be
    #   ${SCRATCH}/${PROJECT}/Thetas
SCRATCH=

#   Define the region being looked at
#       Optional, but ANGSD is expensive to run without specifying regions to look at
REGIONS=

#   Parameters that are specified in Common_Config
UNIQUE_ONLY=0
MIN_BASEQUAL=20
BAQ=1
MIN_IND=1
GT_LIKELIHOOD=2
MIN_MAPQ=30
N_CORES=32
DO_MAJORMINOR=1
DO_MAF=1

##############################################################################################

#   Pest file
#       This is the output from the site frequency spectrum wrapper
#       This should end in "_DerivedSFS"
PEST=

#   Thetas Parameters
#       Listed below are the defaults, please modify for your samples
DO_SAF=2
DO_THETAS=1
OVERRIDE=false
SLIDING_WINDOW=false
WIN=50000
STEP=10000
